### ISSUE TITLE
Ready for Grading Week 2 Assignment

### ISSUE THREAD

**Issue by ajjacques-matc** [madisoncollege-it-programs/python-scripting-ajjacques-matc#1]

**Comment by cethenmc** [comment]
Hi, Tony.  Two things:
1)  You have Week 2, Assignment #2 out here.  You have not pushed out Week 2, Assignment #1 yet.  So this issue is mislabeled.  Please edit it to be Week 2, Assignment #2.
2)  I would like you to update your first-script.py before I grade it, so you can run it from the command line.

Your first line should always be the following for your scripts. In this way, if you are running from the command line it will know what interpreter to use. Will you please add this line to the top of your first-script.py code?

#!/usr/bin/env python3

Recall from the videos, you may also need to issue a chmod command to modify the rights to make it executable.

chmod u+x first-script.py

After this, you can execute from the command line.

./first-script.py

Please be so kind as to resubmit it, so...

1. modify the file in NetLab with the added line at the top.
2. update the file to be executable.
3. add the file to staging (git add .)
4. commit the file to your local repo. (git commit -m "changes requested to run from command line")
5. push to the git hub repository (git push)
6. reply to this same issue, saying you have completed these steps

Thanks.

~Chris

**Comment by ajjacques-matc** [comment]
Fixed issue with Assignment #1

**Comment by cethenmc** [comment]
Tony.  You closed the issue, but you only fixed one item.  Are you going to create a second issue when you complete Week 2 Assignment 1?  The GitHub assignment.

Thanks.

Chris

[signature_146958654]
Chris Ethen| Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>
