### ISSUE TITLE
week 11 arguments.py  assignment ready for grading

### ISSUE THREAD

**Issue by ajjacques-matc** [madisoncollege-it-programs/python-scripting-ajjacques-matc#13]

**Comment by cethenmc** [comment]
I really like how you decided to move the required field as the first argument, but in the future when you are trying to match a picture of what we set up, it would be very helpful to me if you kept it in the same order as presented.  

In the picture below.  Yours is left, and the document you were to match using concepts learned in the week's lesson is on the right.

-m was not set up as a basic argument.
-integer was not set to required
-a lot of naming different than asked
-not printing the way asked (and what was asked)
-metavar missing on some

I recorded a 5 out of 8 for now, please correct issues and resubmit soon.  Please correct the order since you are in there anyway.

 
![image](https://user-images.githubusercontent.com/112707666/202757950-719a8ae0-21ef-4afe-ad21-5d417953d175.png)

**Comment by cethenmc** [comment]
Closing ticket.  With a great job on the final exam, you secured an A without needing corrections on this lab!
